### ISSUE TITLE
Missing ")" after argument list.

### ISSUE THREAD

**Issue by Crowes** [Wrappa/Core#1]
On `require('wrappa-core'), an error is thrown. 

```
C:\Users\admin.crowe\Documents\GitHub\Kioska\Queue\node_modules\wrappa-core\src\Domain.js:63
      DomainNameServer.lookupService(hostIP, hostPort, (hostError, hostHostname) {
                                                                               ^

SyntaxError: missing ) after argument list
    at createScript (vm.js:74:10)
    at Object.runInThisContext (vm.js:116:10)
    at Module._compile (module.js:533:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\admin.crowe\Documents\GitHub\Kioska\Queue\node_modules\wrappa-core\core.js:4:11)
```

**Comment by Crowes** [comment]
Fixed it by correcting an Arrow function declaration.
