### ISSUE TITLE
ReferenceError: FileSystem is not defined.

### ISSUE THREAD

**Issue by Crowes** [Wrappa/Core#3]
```
ReferenceError: FileSystem is not defined
    at new FileStreamer (C:\Users\admin.crowe\Documents\GitHub\Kioska\Queue\node_modules\wrappa-core\src\types\FileStreamer.js:18:33)
    at Function.streamFile (C:\Users\admin.crowe\Documents\GitHub\Kioska\Queue\node_modules\wrappa-core\src\File.js:111:12)
    at Logger.worker (C:\Users\admin.crowe\Documents\GitHub\Kioska\Queue\components\Logger.js:109:47)
    at <anonymous>

```

**Comment by Crowes** [comment]
Reference to FileSystem did not exist in FileStreamer class.
